- name: RHEL Testing
  hosts: all
  gather_facts: false
  become: all

  tasks:
    - name: Install mariadb RHEL8
      ansible.builtin.dnf:
        name: 
          - httpd < 2.4
          - mariadb
        state: absent