- name: RHEL Testing
  hosts: 10.1.0.30
  gather_facts: false
  become: true

  tasks:
    - name: Install mariadb RHEL8
      ansible.builtin.dnf:
        name: 
          - httpd < 2.4
          - mariadb
        state: absent